---
- name: Icinga 2 Fundamentals
  type: training
  date: 2018-07-10
  duration: 4
  city: Nuremberg
  country: Germany
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga_trainings/
- name: Icinga 2 Fundamentals
  type: training
  date: 2018-07-16
  duration: 4
  city: Zurich
  country: Switzerland
  partner: Linuxfabrik
  partner_link: https://www.linuxfabrik.ch/
  registration_link: https://www.linuxfabrik.ch/schulungen/icinga
- name: Icinga 2 Fundamentals
  type: training
  date: 2018-08-20
  duration: 4
  city: Zurich
  country: Switzerland
  partner: Linuxfabrik
  partner_link: https://www.linuxfabrik.ch/
  registration_link: https://www.linuxfabrik.ch/schulungen/icinga
- name: Icinga 2 Fundamentals
  type: training
  date: 2018-09-13
  duration: 4
  city: Zurich
  country: Switzerland
  partner: Linuxfabrik
  partner_link: https://www.linuxfabrik.ch/
  registration_link: https://www.linuxfabrik.ch/schulungen/icinga
- name: Icinga 2 Advanced
  type: training
  date: 2018-09-18
  duration: 3
  city: Nuremberg
  country: Germany
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga_trainings/
- name: Icinga 2 Fundamentals
  type: training
  date: 2018-09-26
  duration: 4
  city: The Hague
  country: Netherlands
  partner: OlinData
  partner_link: https://www.olindata.com/
  registration_link: https://www.olindata.com/en/training/icinga-2-fundamentals
- name: Icinga 2 Fundamentals
  type: training
  date: 2018-10-01
  duration: 4
  city: Zurich
  country: Switzerland
  partner: Linuxfabrik
  partner_link: https://www.linuxfabrik.ch/
  registration_link: https://www.linuxfabrik.ch/schulungen/icinga
- name: Icinga 2 Fundamentals
  type: training
  date: 2018-10-09
  duration: 4
  city: Nuremberg
  country: Germany
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga_trainings/
- name: Icinga 2 Fundamentals
  type: training
  date: 2018-10-23
  duration: 4
  city: Hannover
  country: Germany
  partner: axxeo GmbH
  partner_link: https://www.axxeo.de/leistungen/monitoring/
  registration_link: https://www.axxeo.de/leistungen/schulungen/workshop-icinga-2/
- name: Icinga 2 Advanced
  type: training
  date: 2018-11-20
  duration: 3
  city: Nuremberg
  country: Germany
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga_trainings/
- name: Icinga 2 Fundamentals
  type: training
  date: 2018-11-20
  duration: 4
  city: Zurich
  country: Switzerland
  partner: Linuxfabrik
  partner_link: https://www.linuxfabrik.ch/
  registration_link: https://www.linuxfabrik.ch/schulungen/icinga
- name: Icinga 2 Fundamentals
  type: training
  date: 2018-12-10
  duration: 4
  city: Zurich
  country: Switzerland
  partner: Linuxfabrik
  partner_link: https://www.linuxfabrik.ch/
  registration_link: https://www.linuxfabrik.ch/schulungen/icinga
