---
- name: Icinga Director Workshop
  type: training
  date: 2019-11-12
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-director-workshop/
- name: Icinga 2 Advanced
  type: training
  date: 2019-11-26
  duration: 3
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
- name: Icinga 2 Fundamentals
  type: training
  date: 2019-12-10
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga 2 Fundamentals
  type: training
  date: 2019-12-10
  duration: 4
  city: Zurich
  country: Switzerland
  language: german
  partner: Linuxfabrik
  partner_link: https://www.linuxfabrik.ch/
  registration_link: https://www.linuxfabrik.ch/schulungen/icinga
- name: Icinga 2 Fundamentals
  type: training
  date: 2019-12-10
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga Module Development
  type: training
  date: 2019-12-19
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-web-module-development/
- name: Icinga with Puppet Workshop
  type: training
  date: 2020-01-08
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-2-und-puppet-workshop/
- name: Icinga 2 Advanced
  type: training
  date: 2020-01-21
  duration: 3
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
- name: Icinga Module Development
  type: training
  date: 2020-02-04
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-web-module-development/
- name: Icinga Director Workshop
  type: training
  date: 2020-03-03
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-director-workshop/
- name: Icinga 2 Advanced
  type: training
  date: 2020-03-10
  duration: 3
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-03-31
  duration: 4
  city: Hannover
  country: Germany
  language: german
  partner: axxeo GmbH
  partner_link: https://www.axxeo.de/leistungen/monitoring/icinga/
  registration_link: https://www.axxeo.de/leistungen/schulungen/workshop-icinga-2/
- name: Icinga Module Development
  type: training
  date: 2020-04-01
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-web-module-development/
- name: Icinga Essentials Workshop
  type: training
  date: 2020-05-12
  duration: 1
  city: Amsterdam
  country: Netherlands
  language: english
  partner: Icinga GmbH
  partner_link: https://icingaconf.com/workshops/
  registration_link: https://icingaconf.com/
- name: Icinga Director Workshop
  type: training
  date: 2020-05-12
  duration: 1
  city: Amsterdam
  country: Netherlands
  language: english
  partner: Icinga GmbH
  partner_link: https://icingaconf.com/workshops/
  registration_link: https://icingaconf.com/
- name: Icinga Director Workshop
  type: training
  date: 2020-06-23
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-director-workshop/
- name: Icinga 2 Advanced
  type: training
  date: 2020-07-21
  duration: 3
  city: Nuremberg
  country: Germany
  language: english
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-09-15
  duration: 4
  city: Hannover
  country: Germany
  language: german
  partner: axxeo GmbH
  partner_link: https://www.axxeo.de/leistungen/monitoring/icinga/
  registration_link: https://www.axxeo.de/leistungen/schulungen/workshop-icinga-2/
- name: Icinga with Puppet Workshop
  type: training
  date: 2020-09-22
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-2-und-puppet-workshop/
- name: Icinga 2 Advanced
  type: training
  date: 2020-10-06
  duration: 3
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
- name: Icinga Director Workshop
  type: training
  date: 2020-10-20
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-director-workshop/
- name: Icinga Module Development
  type: training
  date: 2020-12-08
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-web-module-development/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-02-04
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-05-26
  duration: 4
  city: Nuremberg
  country: Germany
  language: english
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-07-07
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-09-22
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-12-01
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga 2 Advanced
  type: training
  date: 2020-12-08
  duration: 3
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
- name: Icinga Module Development
  type: training
  date: 2020-12-08
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-web-module-development/
