---
- name: Icinga 2 Fundamentals
  type: training
  date: 2022-02-08
  duration: 4
  city: Online Class
  country: Germany
  language: english
  partner: Dexor GmbH
  partner_link: https://dexor.de/en/icinga2-for-monitoring-of-the-infrastructure/
  registration_link: https://dexor.de/en/icinga2-training-registration-form/
- name: Icinga 2 Advanced
  type: training
  date: 2022-02-21
  duration: 3
  city: Online Class
  country: Germany
  language: english
  partner: Dexor GmbH
  partner_link: https://dexor.de/en/icinga2-for-monitoring-of-the-infrastructure/
  registration_link: https://dexor.de/en/icinga2-training-registration-form/
- name: Icinga 2 Fundamentals
  type: training
  date: 2022-05-03
  duration: 4
  city: Online Class
  country: Germany
  language: english
  partner: Dexor GmbH
  partner_link: https://dexor.de/en/icinga2-for-monitoring-of-the-infrastructure/
  registration_link: https://dexor.de/en/icinga2-training-registration-form/
- name: Icinga 2 Advanced
  type: training
  date: 2022-05-16
  duration: 3
  city: Online Class
  country: Germany
  language: english
  partner: Dexor GmbH
  partner_link: https://dexor.de/en/icinga2-for-monitoring-of-the-infrastructure/
  registration_link: https://dexor.de/en/icinga2-training-registration-form/
- name: Icinga 2 Fundamentals
  type: training
  date: 2022-09-05
  duration: 4
  city: Online Class
  country: Germany
  language: english
  partner: Dexor GmbH
  partner_link: https://dexor.de/en/icinga2-for-monitoring-of-the-infrastructure/
  registration_link: https://dexor.de/en/icinga2-training-registration-form/
- name: Icinga 2 Advanced
  type: training
  date: 2022-09-19
  duration: 3
  city: Online Class
  country: Germany
  language: english
  partner: Dexor GmbH
  partner_link: https://dexor.de/en/icinga2-for-monitoring-of-the-infrastructure/
  registration_link: https://dexor.de/en/icinga2-training-registration-form/
- name: Icinga 2 Fundamentals
  type: training
  date: 2022-11-15
  duration: 4
  city: Online Class
  country: Germany
  language: english
  partner: Dexor GmbH
  partner_link: https://dexor.de/en/icinga2-for-monitoring-of-the-infrastructure/
  registration_link: https://dexor.de/en/icinga2-training-registration-form/
- name: Icinga 2 Advanced
  type: training
  date: 2022-11-28
  duration: 3
  city: Online Class
  country: Germany
  language: english
  partner: Dexor GmbH
  partner_link: https://dexor.de/en/icinga2-for-monitoring-of-the-infrastructure/
  registration_link: https://dexor.de/en/icinga2-training-registration-form/
