---
- name: Icinga 2 Fundamentals
  type: training
  date: 2019-09-10
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga 2 Fundamentals
  type: training
  date: 2019-09-16
  duration: 4
  city: Zurich
  country: Switzerland
  language: german
  partner: Linuxfabrik
  partner_link: https://www.linuxfabrik.ch/
  registration_link: https://www.linuxfabrik.ch/schulungen/icinga
- name: Icinga 2 Advanced
  type: training
  date: 2019-09-17
  duration: 3
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
- name: Icinga 2 Fundamentals
  type: training
  date: 2019-09-24
  duration: 4
  city: Hannover
  country: Germany
  language: german
  partner: axxeo GmbH
  partner_link: https://www.axxeo.de/leistungen/monitoring/
  registration_link: https://www.axxeo.de/leistungen/schulungen/workshop-icinga-2/
- name: Icinga with Puppet Workshop
  type: training
  date: 2019-10-08
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-2-und-puppet-workshop/
- name: Icinga Module Development
  type: training
  date: 2019-10-10
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-web-module-development/
- name: Icinga 2 Fundamentals
  type: training
  date: 2019-10-22
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga 2 Advanced
  type: training
  date: 2019-11-26
  duration: 3
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
- name: Icinga 2 Fundamentals
  type: training
  date: 2019-12-10
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga 2 Fundamentals
  type: training
  date: 2019-12-10
  duration: 4
  city: Zurich
  country: Switzerland
  language: german
  partner: Linuxfabrik
  partner_link: https://www.linuxfabrik.ch/
  registration_link: https://www.linuxfabrik.ch/schulungen/icinga
- name: Icinga Module Development
  type: training
  date: 2019-12-19
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-web-module-development/
