---
- name: Icinga Fundamentals + Director (Virtual Class)
  type: training
  date: 2020-05-25
  duration: 4
  city: Atlanta
  country: USA
  language: english
  partner: Shadow-Soft
  partner_link: https://shadow-soft.com/monitoring/
  registration_link: https://shadow-soft.com/icinga-training-virtual/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-05-26
  duration: 4
  city: Online Class
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga Director Workshop
  type: training
  date: 2020-06-23
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-director-workshop/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-07-07
  duration: 4
  city: Online Class
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga 2 Advanced
  type: training
  date: 2020-07-21
  duration: 3
  city: Online Class
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-09-15
  duration: 4
  city: Hannover
  country: Germany
  language: german
  partner: axxeo GmbH
  partner_link: https://www.axxeo.de/leistungen/monitoring/icinga/
  registration_link: https://www.axxeo.de/leistungen/schulungen/workshop-icinga-2/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-09-22
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga with Puppet Workshop
  type: training
  date: 2020-09-22
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-2-und-puppet-workshop/
- name: Icinga 2 Advanced
  type: training
  date: 2020-10-06
  duration: 3
  city: Berlin
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
- name: Icinga Director Workshop
  type: training
  date: 2020-10-20
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-director-workshop/
- name: Icinga 2 Fundamentals
  type: training
  date: 2020-12-01
  duration: 4
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/en/trainings/icinga-fundamentals/
- name: Icinga Module Development
  type: training
  date: 2020-12-08
  duration: 2
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-web-module-development/
- name: Icinga 2 Advanced
  type: training
  date: 2020-12-08
  duration: 3
  city: Nuremberg
  country: Germany
  language: german
  partner: NETWAYS GmbH
  partner_link: https://www.netways.de/en/products/icinga/
  registration_link: https://www.netways.de/trainings/icinga-advanced/
